--- 
title: "Стихи о любви"
author: "Автор — зыбко-иллюзорный"
date: "2022 год"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: article 
mainfont: "Noto Sans"
language: ru
description: "Стихи о любви."
---
# О книге {#about}

Стихи о любви с религиозными мотивами.

__Лицензия:__ [Creative Commons Attribution Share Alike 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.ru).

# Стихи {#poetry}

## О настоящем и ненастоящем времени {#time}

ощущение, что настоящее не такое уж и настоящее  
а прошлое брошено  
одни лишь карты дорожные  

их много – но нет достижений  
скорее набор цепей и оков  
и мёртвый груз тупиков  
лежащих в тайнике Тени  

бегу от себя пытаясь спастись у других  
бегу от других пытаясь спасти себя от других  
себя от других в голове  
и других от моего образа в них  

но прятать себя в себе нету силы  

голоса воют невыносимо  
но то что они говорят  
вряд ли запишешь в столбик  
или выпишешь в ряд  

хоть прошлое прошлое на произвол брошено  
а пришлое прошлое кишит произволом  
похоже, что Тень твоя так и прячется в прошлом  

а прошлое с Тенью тебя поедают  

тогда-то и злые личины спадают  
что кормятся чашей распадов  
не лучший боюсь из раскладов  

и холод могильный в душе  
чьё существование отрицал столько лет  
и самость под грузом привычек  

а из боекомплекта  
только мобильный  
плацкартный билет  
и коробок спичек  

горите фантомы огнём  
экспресс уже на подходе  

а Проводник примет всех  
и каждый будет спасён  

Он чей-то посланник  
вроде  

_Его не волнуют контроль или власть_  
_свобода — подарок для равных_  

_но хватит ли сил сей подарок принять_  
_вопрос едва ли не главный_  

## Я, моя тень и мой фантом {#phantom}

когда стало ясно, что я остаюсь один  
остались только мы трое:  
я,  
мой Фантом  
и Тень  

мне не о чем говорить с ними  
и, по правде, их общество тяготит меня больше  
чем общество окружающих  

но те же окружающие наделяют меня ими  
как обязательными атрибутами  

послать бы их всех на три буквы, но  
каждая буква  
плотно сцепилась с другими  

объясняю Тени, что никакой Тени у меня нет  
что Фрейд был просто шутником и старым извращенцем  
а Юнг — сумасшедшим  
в общем, оба были очень странными типами  

говорю Тени о том,  
что странно верить во все эти синхроничности с архетипами  

Тени плевать.  

раз уж её наличие у меня — стереотип общества  
(не очень–то спорить с обществом хочется)  
значит, она обязательно есть  
точка  

откуда взялся Фантом  
я вообще не имею понятия  

я думал успокоить других  
заверить, что это не я  

скорее уж он — ошибка в их восприятии  
коллективный ассоциативный процесс  
разбавленный стереотипами  
страхами  
травмами  
ассоциациями  

вот только реальность ещё больше увидеть боятся они  

тогда ведь придётся увидеть себя настоящих  

вся ситуация — пат. помогают не сыграть в ящик  
лишь совесть  
свобода воли  

и наличие хоть какого–то элемента контроля  

## Большая колесница и танец {#dance}

учиться сочувствовать  
надеясь найти в этом спасение

ведь сочувствовать — это быть с кем–то  
это вовсе не одиночество

учиться сочувствовать, видя в это  
Божий замысел и Священную Пустоту

сочувствовать так, что выбивает  
все пробки

не остаётся сочувствия вовсе  
а пустота вовсе не та, которую ты искал

эта пустота — не Пустота  
это полное отсутствие чувств  
в этой пустоте вовсе нет смысла

что может заменить ощущение смысла  
ощущение статуса, контроля и власти  
может быть  
но ведь контроль — это всегда иллюзия

а пустота вместо сочувствия  
приводит к своей противоположности

ощущению, что ты один. тотальному одиночеству  
чем больше контроля, тем больше ощущение  
что никого живого вокруг не осталось

чем сильнее люди подчиняются другому человеку  
тем меньше их самих и больше этого человека

эго или, если угодно, нафс становится  
таким толстым и уродливым  
что человек не может рассмотреть ничего  
кроме самого себя  
хоть самого себя не видит

он жаждет всё больше и больше власти  
всё больше объектов статуса, всё больше того  
что он всё равно не сможет унести с собой в могилу

ненависть и разрушения — может быть  
в этом тоже можно найти смысл

но в корне, я верю, всегда есть поломка  
которая является внешней по отношению  
к человеку

и наверняка, пробивая асфальт  
боли, одиночества, страха смерти

растёт хоть маленький, но цветок  
и важно, чтобы он получил немного воды  
и немного солнца

тогда, наверное, в этом можно найти  
любящую доброту и любовь  
сказать «на благо всех живых существ»  
и заполнить пустоту внутри

и тогда где–то рядом может промелькнуть  
та самая Пустота, которую так долго искал  
и которая никуда не уходила  
или Божий промысел

и тогда ты увидишь,  
что милосердия и милости во всех мирах  
больше, чем гнева

«дзынь-дзынь», прозвенит будильник  
чтобы ты мог начать свой день  
с Истины, у которой нет имени  
и того, что не может быть выражено словами  

священная Пустота. Божий промысел. любовь.  
тайны, сокрытые в тишине и молчании

шум ветра и карта Небес

## Немного о природе любви {#love}

любовь начинается там, где заканчиваюсь «я»  
там, где заканчиваюсь я, вообще много всего интересного:  
например, смерть  
например, Бог  
например, суть вещей  
например, свобода  

в любви гораздо больше Бога, чем смерти  
вернее, в ней вовсе нет смерти  
в любви есть понимание, что смерти нет вовсе  

наверное, именно с любви начинается религиозное чувство  
наверное, именно с любви начинается пробуждение от многих из иллюзий  
например, иллюзии о том, что человек одинок  

наверное, именно с любви начинается Бог  

сути вещей в любви больше, чем свободы  
любовь уменьшает то, что тебе казалось свободой  
и даёт взамен настоящую свободу  

возможно, в любви есть всё. и всё есть любовь  
возможно, любовь на самом деле о том, что нет ничего, кроме Бога  

одни считают любовь иллюзией  
другие – освобождением от иллюзий  
я думаю, что правы последние  

в любви есть суть вещей  
в любви есть прекрасное  
прекрасное вообще основано на любви

и самое прекрасное – в любви нет надежды  
надежда не нужна, когда есть жизнь  

## Путеводная звезда за линией горизонта {#star}

понять, что такое любовь относительно просто.  
представьте, что вы оказались за линией горизонта:  

здесь есть много интересных вещей и явлений,  
здесь очевидно чьё-то невидимое присутствие.  
наверное, это Бог.  
да, скорее всего.  
спасибо ему за это.  

здесь есть суть вещей и разгадки.  
но разгадки — последнее, что тебе нужно.  
тебе не нужны тайны и не нужны ответы.  
да и ты здесь не ради себя.  

это не значит, что ты пытаешься  
чувствовать радость всё время.  

скорее, это значит, что ты видишь на небосводе  
путеводную звезду,  
даже оставаясь за линией  
горизонта.  

## Пустыня {#desert}

потеряв себя, можно обрести взамен очень многое.  

от какого, в сущности, пустяка следует отказаться,  
чтобы обрести подлинные сокровища!  

такое странное, неясное, невнятное,  
непонятно откуда взявшееся ощущение своего "я".  

бескрайняя пустыня, где почти нет островков жизни,  
но есть горизонт и вкрапления оазисов  
(не перепутать бы их с миражами!)  

оазисы — это жизнь.  

если долго вглядываться в оазис,  
может показаться,  
что никакой пустыни нет  
и никаких миражей нет.  

случайно заглянув чуть дальше горизонта,  
можно увидеть то, что казалось потерянным,  
пока ты блуждал по пустыне.  

наверное, это Бог  
и множество сопутствующих ему явлений.  
сложно понять это, когда глаза ослеплены солнцем.  

но даже если после этого ты окажешься в пустыне,  
с тобой останется подозрение,  
что как раз это и есть настоящее  
а пустыня всегда была иллюзией.  

## Дихотомия {#dichotomy}

свой первый раз, когда я задумался  
о проблеме детерминизма,  
свободы воли  
и той дихотомической по своей природе  
морали, которая присутствует в культурах,  
порождённых авраамическими религиями,  
я помню плохо.  

наверное, ботаникам потому и навешивают тумаков,  
чтобы не задумывались над такими вопросами  
и не ломали себе жизнь.  

если твой выбор не имеет значения —  
кому принадлежат победы, а кому поражения?  

а если выбор — всего лишь иллюзия,  
в чём виноваты вообще могут люди быть?  
но это была лишь прелюдия  

к полному выносу мозга.  

не помню, когда вместо меня  
в первый раз начала говорить моя боль.  

она была куда более уверенной и, кажется,  
куда более гармоничной и цельной личностью,  
чем я.  

а я был всего лишь мешком,  
неуклюжим и бесформенным,  
вечно испуганным и беспомощным  
ребёнком.  

я много думал о линейности времени,  
параллельных мирах, шизофазии Зеланда,  
которая мне давно параллельна.  

а позже, что жизнь — лишь форма  
существования белковых тел:  
только цепочки нуклеотидов  
и пары аллелей.  

я думал о том, как вернуть то,  
чего уже не вернёшь.  
или снова вернуться туда,  
где сделал неправильный выбор,  

надеясь на то, что на этот раз  
выбор ты сделаешь точно правильный  
и точно сам.  

а пока я думал об этом —  
возможностей становилось всё меньше,  
а поводов тосковать по ним - всё больше.  

кажется, так и правда было комфортнее.  

я ходил без цели —  
руки в карманах,  
голова в капюшоне  
и никак не мог научиться  
озираться по сторонам  

или хотя бы смотреть под ноги:  

так было бы проще рассмотреть руки помощи,  
увы, уже окоченевшие, тронутые трупными пятнами.  
главное — не наступайте на них пятками!  

наверное, это судьба тех, кто помогает:  
сначала ты протягиваешь руку помощи,  
потом протягиваешь ноги.  

я и сам такой:  

тем не менее сам пишу этот текст рукой  
которая одновременно протянута, разжата,  
а пульс нитевидный.  

до чего удивляет мироздание!  

так много мыслительных потоков,  
таких быстрых!  
гнаться за ними  
или гнать их?  
или это они гонят:  
гонят меня куда-то или гонят вообще?  

какой вообще дурак станет доверять своим мыслям?  

казалось, что вот-вот сорвёт тормоза,  
зато прокачусь с комфортом в последнюю поездку.  

но, кажется, внутри всё ещё оставалось  
то, что было готово дёрнуть стоп-кран.  
испуганное,  
уязвимое,  
удивлённое:  

_— а где в этом поезде Проводник?_  

вопрос, который волновал меня и раньше  
в далёком детстве.  
я прятался в деревенском домике от грозы.  
в доме выбило пробки,  
света и электричества не было.  

и было очень страшно,  
но почему-то свежо  
и свободно.  

наверное,  
суть парадокса вагонетки в том,  
чтобы успеть принять хоть какое-то решение  
пока в этом есть смысл.
